### ISSUE TITLE
Problem rebuilding to electron with lock-your-windows

### ISSUE THREAD

**Issue by danilqweasd12321** [Aldaviva/lock-your-windows#6]
```
> .\node_modules\.bin\electron-rebuild.cmd
The projects in this solution are built sequentially. To enable parallel build, add the "-m" option.
⠏ Building module: lock-your-windows, Completed: 1  winlock.cpp
⠴ Building module: lock-your-windows, Completed: 1  bindings.cpp
⠸ Building module: lock-your-windows, Completed: 1
C:\Users\user\Documents\notify\node_modules\lock-your-windows\src\main\c++\bindings.cpp(13,47): error C2039: "CreationContext": Not a member of "v8::Object".[C:\Users\user\Documents\notify\node_modules\lock-your-windows\build\winlock.vcxproj]
C:\Users\user\.electron-gyp\23.1.4\include\node\v8-value-serializer.h(22): message : см. объявление "v8::Object" [C:\Users\user\Documents\notify\node_modules\lock-your-windows\build\winlock.vcxproj]
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild 'C:\Users\user\Documents\notify\node_modules\lock-your-windows'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1     



Error: node-gyp failed to rebuild 'C:\Users\user\Documents\notify\node_modules\lock-your-windows'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1


    at NodeGyp.rebuildModule (C:\Users\user\Documents\notify\node_modules\electron-rebuild\lib\src\module-type\node-gyp.js:120:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ModuleRebuilder.rebuildNodeGypModule (C:\Users\user\Documents\notify\node_modules\electron-rebuild\lib\src\module-rebuilder.js:98:9)
    at async ModuleRebuilder.rebuild (C:\Users\user\Documents\notify\node_modules\electron-rebuild\lib\src\module-rebuilder.js:128:14)
    at async Rebuilder.rebuildModuleAt (C:\Users\user\Documents\notify\node_modules\electron-rebuild\lib\src\rebuild.js:149:13)
    at async Rebuilder.rebuild (C:\Users\user\Documents\notify\node_modules\electron-rebuild\lib\src\rebuild.js:112:17)
    at async C:\Users\user\Documents\notify\node_modules\electron-rebuild\lib\src\cli.js:158:9
```

**Comment by danilqweasd12321** [comment]
How timely!
I just woke up!

**Comment by Aldaviva** [comment]
Good morning! The error you're seeing appears just as a warning when I build the module (not in Electron). It recommends that I change `lock-your-windows\src\main\c++\bindings.cpp` from
```cpp
v8::Local<v8::Context> context = exports->CreationContext();
```
to
```cpp
MaybeLocal<Context> context = GetCreationContext();
```
but this breaks my build. I think I may have to update the version of `nan` I am using, or maybe I'm just not importing some header file.

I'm building with `node-gyp` 9.3.1 and Node 18.15.0.

**Comment by Aldaviva** [comment]
OK it seems like switching from using an `Init` function to the `NAN_MODULE_INIT` macro makes it compile without any warnings. This was based on [Nan's `async_pi_estimate` example](https://github.com/nodejs/nan/blob/dd5edf87e84abb678befe754cd55c7b99326248a/examples/async_pi_estimate/addon.cc#L22).

```cpp
NAN_MODULE_INIT(Init) {
    Nan::Set(target, Nan::New("isLocked").ToLocalChecked(), Nan::New<v8::FunctionTemplate>(IsLocked)->GetFunction(Nan::GetCurrentContext()).ToLocalChecked());
    Nan::Set(target, Nan::New("lock").ToLocalChecked(), Nan::New<v8::FunctionTemplate>(Lock)->GetFunction(Nan::GetCurrentContext()).ToLocalChecked());
}
```

While this does fix the build warnings I was seeing, I don't know if this will fix your build using Electron-gyp. To verify this, would you like to edit `lock-your-windows/src/main/c++/bindings.cpp` on your computer to replace the entire `void Init(v8::Local<v8::Object> exports)` function with the `NAN_MODULE_INIT` block above? I also bumped the `nan` dependency to `^2.17.0` in `package.json`.

If that change builds for you without any errors, I can release it as a new version of `lock-your-windows` on NPM.

**Comment by danilqweasd12321** [comment]
![603_31BN](https://user-images.githubusercontent.com/37021861/226835145-a1c671f1-67e2-4aca-ab91-e01f91a8e7c9.png)
it should so?

**Comment by danilqweasd12321** [comment]
![309_64lX](https://user-images.githubusercontent.com/37021861/226835473-0dce8974-e672-4545-8ab5-6bdb6f2e8e08.png)
i setted the error the screenshot

**Comment by Aldaviva** [comment]
Can you replace the entire contents of that file with
```cpp
#include <nan.h>
#include "winlock.h"

void IsLocked(const Nan::FunctionCallbackInfo<v8::Value>& info){
    info.GetReturnValue().Set(Nan::New(isWorkstationLocked()));
}

void Lock(const Nan::FunctionCallbackInfo<v8::Value>& info){
    lockWorkstation();
}

NAN_MODULE_INIT(Init) {
    Nan::Set(target, Nan::New("isLocked").ToLocalChecked(), Nan::New<v8::FunctionTemplate>(IsLocked)->GetFunction(Nan::GetCurrentContext()).ToLocalChecked());
    Nan::Set(target, Nan::New("lock").ToLocalChecked(), Nan::New<v8::FunctionTemplate>(Lock)->GetFunction(Nan::GetCurrentContext()).ToLocalChecked());
}

NODE_MODULE(winlock, Init)
```
and then try to run your build again?

**Comment by danilqweasd12321** [comment]
YEEEY REBUILD IS DONNNEEE
`✔ Rebuild Complete`

**Comment by danilqweasd12321** [comment]
also fully console
```
⠸ Building module: lock-your-windows, Completed: 1Выполняется последовательная сборка проектов в этом решении. Чтобы включить параллельную сборку, добавьте параметр "-m".
⠇ Building module: lock-your-windows, Completed: 1  winlock.cpp
⠴ Building module: lock-your-windows, Completed: 1  bindings.cpp
⠴ Building module: lock-your-windows, Completed: 1  win_delay_load_hook.cc
⠏ Building module: lock-your-windows, Completed: 1  Создание кода
  Previous IPDB not found, fall back to full compilation.
⠋ Building module: lock-your-windows, Completed: 1  All 90 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Создание кода завершено
⠙ Building module: lock-your-windows, Completed: 1  winlock.vcxproj -> C:\Users\user\Documents\notify\node_modules\lock-your-windows\build\Release\\winlock.node
⠸ Building module: lock-your-windows, Completed: 1  Copying C:\Users\user\Documents\notify\node_modules\lock-your-windows\build\Release\/winlock.node to ..\target
  Скопировано файлов:         1.
✔ Rebuild Complete
```

**Comment by danilqweasd12321** [comment]
lets see if it works....

**Comment by danilqweasd12321** [comment]
ok it works, no errors 
```
Error: The module '/path/to/native/module.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION $XYZ. This version of Node.js requires
NODE_MODULE_VERSION $ABC. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

**Comment by danilqweasd12321** [comment]
ok everything is works, thanks for help ✔

**Comment by Aldaviva** [comment]
OK great, I will work on releasing this as a new version 0.0.2 on NPM soon.

I'm not sure what that `NODE_MODULE_VERSION` warning means, it should be using your current Node version and copying your newly-rebuilt `lock-your-windows\target\winlock.node` file.

**Comment by danilqweasd12321** [comment]
well idk why so, i show wait

**Comment by danilqweasd12321** [comment]
![093_GBek](https://user-images.githubusercontent.com/37021861/226837405-d033d210-34bc-4f7e-8908-24f4689d18e0.png)
here error: ❌

**Comment by danilqweasd12321** [comment]
but before fixing code and compling then compling is passed and everything is works with electron

**Comment by Aldaviva** [comment]
Hmm, I wonder if there are two different installation versions of Node or Electron on your computer.

On my computer, I have this version:
```text
> node -v
v18.15.0
> node -p "process.versions.modules"
108
```

**Comment by danilqweasd12321** [comment]
![629_KUw1](https://user-images.githubusercontent.com/37021861/226839609-9acc2037-2b98-4b8e-9bd3-c24c470c6a3c.png)
🤔

**Comment by danilqweasd12321** [comment]
ooo maybe electron was different version...

**Comment by danilqweasd12321** [comment]
idk how to get version in electron 🤷

**Comment by danilqweasd12321** [comment]
i just using `npm start`
Also 
```json
"scripts": {
    "start": "electron .",
}
```

**Comment by Aldaviva** [comment]
I tried running the latest Current version of Node (19.8.1) but that only has NODE_MODULE_VERSION 111, not 113, unfortunately. And the latest nightly Node 20.0.0 only has NODE_MODULE_VERSION 112.

Maybe there's some way to make Electron run this build for you automatically instead of having to manually match Node versions.

**Comment by danilqweasd12321** [comment]
Well, I don’t know, and in general I’m not going to release this project of mine, this project is intended for me

**Comment by danilqweasd12321** [comment]
![106_TKfm](https://user-images.githubusercontent.com/37021861/226842724-9b51de3e-1fee-47c7-ad05-f5162e924a61.png)
i found a version by using `console.log(process.versions.modules)`
you see a `113`
(dont mind about port lol they used for preventing duplicates instances XDDD)
also version node is same

**Comment by Aldaviva** [comment]
I have published [`lock-your-windows@0.0.2`](https://www.npmjs.com/package/lock-your-windows/v/0.0.2) with the fix for the `error C2039: "CreationContext": Not a member of "v8::Object"` message.

**Comment by danilqweasd12321** [comment]
Great, i think we can close issue?
also we can discord if you want

**Comment by Aldaviva** [comment]
Great, closing issue then.

Maybe changing your `lock-your-windows` version number to `0.0.2` now will let Electron rebuild and fix it?

I don't know anything about Electron so I doubt I would be as helpful as Googling the remaining issue, and my time zone is very different, so I will respectfully decline a Discord session.

**Comment by danilqweasd12321** [comment]
i will try a later

**Comment by danilqweasd12321** [comment]
It complies and works good! and npm is correctly installed!
but unfortunately the error still remains by using not matched version

**Comment by danilqweasd12321** [comment]
now it closed issue and fixed
